from subprocess import run, CalledProcessError
import re

from utils.jarvis import send_to_jarvis

def clean_commit_message(raw_output: str) -> str:
    """Extracts just the commit message string regardless of LLM formatting."""
    # 1. Look for content inside quotes after -m (e.g., git commit -m "feat: my change")
    match = re.search(r'git commit -m\s*["\']([^"\']+)["\']', raw_output)
    if match:
        return match.group(1).strip()
    
    # 2. Look for any line starting with conventional types (feat:, fix:, chore:, etc.)
    match = re.search(r'^(feat|fix|chore|docs|style|refactor)(\(.*\))?:\s*.+$', raw_output, re.MULTILINE)
    if match:
        return match.group(0).strip()
    
    # 3. Fallback: Strip git commands, quotes, and backticks line by line
    clean_lines = []
    for line in raw_output.splitlines():
        line = line.strip()
        if not line or line.startswith("git add") or line.startswith("```"):
            continue
        line = re.sub(r'^git commit -m\s*', '', line)
        line = line.strip('"\'` ')
        if line:
            clean_lines.append(line)
            
    return clean_lines[0] if clean_lines else "chore: update codebase"

def run_command(command : list[str]) -> str:

    try:
        result = run(command, capture_output=True, text=True, check=True)
    except CalledProcessError as e:
        return f"Error: {e.stderr.strip()}"

    return result.stdout

def git_commit():
    # Type hinting
    status: str
    diff_staged: str
    commit_message: str

    # 1. Check status first
    status = run_command(["git", "status", "--short"])

    if not status or status.startswith("Error:"):
        print("No changes detected. Nothing to commit.")
        return

    # 2. Stage changes FIRST so git diff captures everything (including untracked/new files)
    run_command(["git", "add", "."])
    diff_staged = run_command(["git", "diff", "--staged"])

    # Fallback if diff is still empty (e.g., binary files or empty commit)
    if not diff_staged.strip():
        diff_staged = status

    # 3. Construct prompt with accurate staged diff
    prompt = f"""You are an expert Git assistant and senior software developer.

Analyze the git status and diff below and generate a high-quality, descriptive commit message in Conventional Commits format.

RULES FOR GREAT MESSAGES:
1. Always use Conventional Commits format:
   - feat: A new feature or capability
   - fix: A bug fix or patch
   - chore: Maintenance, config changes, or dependency updates
   - docs: Documentation changes
   - style: Formatting or code cleanup without logic changes
   - refactor: Code restructuring without changing behavior
2. Include an accurate scope if applicable, e.g., feat(stt): or fix(git):
3. Explain WHAT changed and WHY in a clear, concise summary (under 60 characters).
4. Be specific based on the actual diff content. Avoid generic messages like "update files" or "fix bugs".

EXAMPLES:
- feat(stt): add push to talk key suppression to prevent terminal character leaks
- fix(git): extract clean commit string from raw model output
- chore(deps): update dependencies in requirements.txt

GIT STATUS:
{status}

GIT DIFF:
{diff_staged}

Write ONLY the commit message:"""

    raw_response = send_to_jarvis(prompt)
    commit_message = clean_commit_message(raw_response)

    if commit_message:
        print(f"Commit message generated by Jarvis:\n{commit_message}")
        allow = input("Do you want to proceed with this commit message? (y/n): ").strip().lower()
        if allow == "y":
            run_command(["git", "commit", "-m", commit_message])
            run_command(["git", "push"])
            print("Changes committed and pushed successfully.")
        else:
            # Unstage files if user cancels the commit
            run_command(["git", "reset"])
            print("Commit cancelled and changes unstaged.")

if __name__ == "__main__":
    git_commit()