from subprocess import run, CalledProcessError

from utils.jarvis import send_to_jarvis

def run_command(command : list[str]) -> str:
    try:
        result = run(command, capture_output=True, text=True, check=True)
    except CalledProcessError as e:
        return f"Error: {e.stderr.strip()}"

    return result.stdout
        

def git_commit():

    # Type hinting
    diff : str
    diff_staged : str = ""
    status : str
    command : list[list[str]]

    command = [
    ["git", "diff"],
    ["git", "diff", "--staged"],
    ["git", "status", "--short"],
    ["git", "add", "."],
    ["git", "push"],
    ]
    
    diff = run_command(command[0])
    if not diff:
        diff_staged = run_command(command[1])
        print("No unstaged changes detected.")
        if diff_staged:
            print("Staged changes found")
    else:
        print("No changes detected. Nothing to commit.")
    status = run_command(command[2])

    commit_message = send_to_jarvis(f"You are an expert Git assistant. Your job is to analyze the provided `git status` and `git diff` and output executable terminal commands. Rules:\n1. Always use Conventional Commits format for the commit message:\n   - feat: A new feature\n   - fix: A bug fix\n   - chore: Maintenance, dependency updates, or tool config\n   - docs: Documentation changes\n   - style: Code style/formatting changes with no logic change\n   - refactor: Code restructuring without adding features or fixing bugs\n2. Keep the commit title concise (under 50 characters).\n3. Output ONLY the raw CLI commands to execute, separated by newlines. No extra commentary or markdown formatting.\n\nExample Output Format:\n git add <file1> <file2>\n git commit -m \"feat(stt): add push-to-talk key suppression\"\n git push\n\nBased on the following git diff:\n{diff}\nAnd the following staged diff:\n{diff_staged}\nAnd the following status:\n{status}\n\nPlease create a concise commit message.")

    if commit_message:
        print(f"Commit message generated by Jarvis:\n{commit_message}")
        allow = input("Do you want to proceed with this commit message? (y/n): ").strip().lower()
        if allow == "y":
            run_command(command[3])
            run_command(["git", "commit", "-m", commit_message])
            run_command(command[4])
            print("Changes committed and pushed successfully.")
        else:
            print("Commit cancelled.")

if __name__ == "__main__":
    git_commit()