from utils.helpers import clean_commit_message, get_context, run_command
from core.jarvis import send_to_jarvis

def generate_git_commit_message(context_input: str = "") -> str | None:
    # 1. Check status
    status = run_command(["git", "status", "--short"])
    if not status or status.startswith("Error:"):
        return None

    # 2. Stage changes
    run_command(["git", "add", "."])
    diff_staged = run_command(["git", "diff", "--staged"])

    if not diff_staged.strip():
        diff_staged = status

    truncated_diff = diff_staged[:1000]
    context = get_context(context_input, status, truncated_diff)

    # 3. Construct prompt
    prompt = f"""
    You are an expert Git assistant and senior software developer.
    Analyze the context, staged files, and git diff below to generate a high-quality commit message following the Conventional Commits format.

    FORMAT SPECIFICATION:
    <type>(<scope>): <description>

    OPTIONAL BODY FORMAT:

    <type>(<scope>): <description>

    <body>

    RULES FOR TYPE & DESCRIPTION:
    1. Valid types: feat, fix, chore, docs, style, refactor, perf, test, build, ci, revert.
    2. Description must explain WHAT changed and WHY in imperative present tense. Keep it concise (under 60 characters).
    3. Include a short body description when helpful. The body must be under 100 words.
    4. Be specific based on actual diff content.

    CONTEXT / INTENT:
    {context}

    Status:
    {status}
    STAGED FILES & DIFF:
    {truncated_diff}

    Write ONLY the final commit message string without markdown backticks or commentary.
    If you include a body, separate it from the subject with a single blank line.
    """

    raw_response = send_to_jarvis(prompt, stream=False)
    commit_message = clean_commit_message(raw_response)

    if not commit_message:
        return None

    return commit_message


def execute_git_commit(commit_message: str) -> str:
    subject, body = commit_message.strip(), ""

    if "\n\n" in subject:
        subject, body = subject.split("\n\n", 1)

    command = ["git", "commit", "-m", subject]
    if body.strip():
        command.extend(["-m", body.strip()])

    run_command(command)
    run_command(["git", "push"])
    return "Changes committed and pushed successfully."


def cancel_git_commit() -> str:
    run_command(["git", "reset"])
    return "Commit cancelled and changes unstaged."


def git_commit(context_input: str = "", auto_confirm: bool = False) -> str:
    commit_message = generate_git_commit_message(context_input)

    if commit_message is None:
        print("No changes detected. Nothing to commit.")
        return "No changes detected. Nothing to commit."

    print(f"\nCommit message generated by Jarvis:\n--> {commit_message}")

    # If called non-interactively (e.g., via Window UI), proceed automatically
    if auto_confirm:
        execute_git_commit(commit_message)
        return f"Committed and pushed successfully:\n\"{commit_message}\""

    # Interactive CLI Mode
    allow = input("Do you want to proceed with this commit message? (y/n): ").strip().lower()
    if allow == "y":
        execute_git_commit(commit_message)
        return f"Changes committed and pushed successfully:\n\"{commit_message}\""

    cancel_git_commit()
    return "Commit cancelled and changes unstaged."

def git_create_branch(branch_name: str):
    command: list[str] = ["git", "switch", "-c", branch_name]
    _ = run_command(command)
    print(f"Created and switched to branch: '{branch_name}'")


def git_delete_branch(branch_name: str):
    command: list[str] = ["git", "branch", "-D", branch_name]
    _ = run_command(command)
    print(f"Deleted branch: '{branch_name}'")


def git_switch_branch(branch_name: str):
    command: list[str] = ["git", "switch", branch_name]
    _ = run_command(command)
    print(f"Switched to branch: '{branch_name}'")


def git_list_branches() -> list[str]:
    command: list[str] = ["git", "branch"]
    result = run_command(command)
    branches = [line.strip().lstrip("* ").strip() for line in result.splitlines()]
    return branches


def git_current_branch() -> str:
    command: list[str] = ["git", "branch", "--show-current"]
    result = run_command(command)
    return result.strip()

# TODO: Add more git-related functions as needed, such as git_merge, git_rebase, etc.