from utils.helpers import clean_commit_message, get_context, run_command
from core.jarvis import send_to_jarvis

def git_commit(context_input: str = ""):
    # 1. Check status first
    status = run_command(["git", "status", "--short"])

    if not status or status.startswith("Error:"):
        print("No changes detected. Nothing to commit.")
        return

    # 2. Stage changes FIRST so git diff captures everything (including untracked files)
    run_command(["git", "add", "."])
    diff_staged = run_command(["git", "diff", "--staged"])

    # Fallback if diff is still empty
    if not diff_staged.strip():
        diff_staged = status

    # Truncate diff to ~1000 chars to optimize Ollama inference speed
    truncated_diff = diff_staged[:1000]

    context = get_context(context_input, status, truncated_diff)
    print("Context received for commit generation.")

    # 3. Construct prompt with accurate staged diff
    prompt = f"""
    You are an expert Git assistant and senior software developer.

    Analyze the context, staged files, and git diff below to generate a high-quality, descriptive commit message following the Conventional Commits format.

    FORMAT SPECIFICATION:
    <type>(<scope>): <description>

    RULES FOR TYPE & DESCRIPTION:
    1. Valid types: feat, fix, chore, docs, style, refactor, perf, test, build, ci, revert.
    2. Description must explain WHAT changed and WHY in imperative present tense (e.g., "add", not "added"). Keep it concise (under 60 characters).
    3. Be specific based on actual diff content. Avoid generic phrases like "update code" or "fix bug".

    RULES FOR SCOPE EVALUATION:
    1. Determine the scope by analyzing the modified directory structure, module names, or primary domain from the staged files and diff.
    2. The scope MUST be a short, lowercase, noun-based identifier representing the affected component or feature area (e.g., auth, cart, api, ui, db, deps).
    3. Use kebab-case for multi-word scopes (e.g., user-profile, payment-gateway).
    4. If changes span multiple unrelated root modules or broad workspace files (e.g., .gitignore, root package.json), either use 'root'/'deps' or omit the scope parentheses entirely.
    5. Do NOT invent vague or overly long scopes.

    EXAMPLES:
    - feat(auth): add Google OAuth2 login support
    - fix(checkout): prevent duplicate order submissions on double-click
    - refactor(user-profile): extract form validation into a custom hook
    - build: upgrade node engine from 18 to 20 in package.json
    - chore(deps): bump lodash from 4.17.20 to 4.17.21

    CONTEXT / INTENT:
    {context}

    Status:
    {status}
    STAGED FILES & DIFF:
    {truncated_diff}

    Write ONLY the final commit message string without markdown backticks or commentary
    """

    raw_response = send_to_jarvis(prompt)
    commit_message = clean_commit_message(raw_response)

    if commit_message:
        print(f"\nCommit message generated by Jarvis:\n--> {commit_message}")
        allow = input("Do you want to proceed with this commit message? (y/n): ").strip().lower()
        if allow == "y":
            run_command(["git", "commit", "-m", commit_message])
            run_command(["git", "push"])
            print("Changes committed and pushed successfully.")
        else:
            # Unstage files if user cancels the commit
            run_command(["git", "reset"])
            print("Commit cancelled and changes unstaged.")


def git_create_branch(branch_name: str):
    command: list[str] = ["git", "switch", "-c", branch_name]
    _ = run_command(command)
    print(f"Created and switched to branch: '{branch_name}'")


def git_delete_branch(branch_name: str):
    command: list[str] = ["git", "branch", "-D", branch_name]
    _ = run_command(command)
    print(f"Deleted branch: '{branch_name}'")


def git_switch_branch(branch_name: str):
    command: list[str] = ["git", "switch", branch_name]
    _ = run_command(command)
    print(f"Switched to branch: '{branch_name}'")


def git_list_branches() -> list[str]:
    command: list[str] = ["git", "branch"]
    result = run_command(command)
    branches = [line.strip().lstrip("* ").strip() for line in result.splitlines()]
    return branches


def git_current_branch() -> str:
    command: list[str] = ["git", "branch", "--show-current"]
    result = run_command(command)
    return result.strip()

# TODO: Add more git-related functions as needed, such as git_merge, git_rebase, etc.